### ISSUE TITLE
Does edgeai-tiovx-apps support PSDK RTOS 08_06_00_11?

### ISSUE THREAD

**Issue by mZhenz** [TexasInstruments/edgeai-tiovx-apps#47]
Hi TI,
Does edgeai-tiovx-apps support PSDK RTOS 08_06_00_11?

**Comment by ravi-rahul** [comment]
We have not tested on 8.6
But it should work, just pull latest edgeai-apps-utils on the target, build and install
https://git.ti.com/cgit/edgeai/edgeai-apps-utils/
Pull this repo and build on target

**Comment by mZhenz** [comment]
Thanks, I will try.

**Comment by mZhenz** [comment]
> We have not tested on 8.6 But it should work, just pull latest edgeai-apps-utils on the target, build and install https://git.ti.com/cgit/edgeai/edgeai-apps-utils/ Pull this repo and build on target

Hi, I find that edgeai-apps-utils is different from edgeai-tiovx-apps. Do you mean I should pull latest edgeai-tiovx-apps on the target?

**Comment by ravi-rahul** [comment]
Sorry for the confusion edgeai apps utils is another repo added post 8.6
Ignore this

Please use this branch for 8.6

https://github.com/TexasInstruments/edgeai-tiovx-apps/tree/8.6_support

Note that apps are not supported, only modules and tests are supported

Also TIDL nodes are not supported

**Comment by mZhenz** [comment]
OK. Thanks.
